#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'gridChallenge' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING_ARRAY grid as parameter.
#

def gridChallenge(arr):
    for j in range(len(arr[0])):
        for i in range(1,len(arr)):
            if arr[i][j]<arr[i-1][j]:
                return "NO"
    return "YES"
for _ in range(int(input())):
    arr = [sorted(input()) for i in range(int(input()))]
    print(gridChallenge(arr))
