#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'pangrams' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def pangrams(s):
    List = []
    for i in range(26):
        List.append(False)
    for c in s.lower():
        if not c == " ":
            List[ord(c) -ord('a')]= True
    for ch in List:
        if ch == False:
            return "not pangram"
    return "pangram"
 

     #return "pangram" if len(s)>=26 else "not pangram"
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = pangrams(s)

    fptr.write(result + '\n')

    fptr.close()
